
version: "3.9"

x-app-env: &app-env
  # Spring profile
  SPRING_PROFILES_ACTIVE: prod

  # Server / ports
  SERVER_PORT: ${SERVER_PORT:-8080}
  ISO8583_PORT: ${ISO8583_PORT:-8037}

  # Database (app-side; points to the Postgres service hostname)
  DB_URL: ${DB_URL:-jdbc:postgresql://fraudengine-postgres:5432/frauddb}
  DB_USERNAME: ${DB_USERNAME:-frauduser}
  DB_PASSWORD: ${DB_PASSWORD:-Fraud}

  # ---------- Fraud Rule ENV Vars ----------
  # High Amount
  FRAUD_HIGH_AMOUNT_ENABLED: ${FRAUD_HIGH_AMOUNT_ENABLED:-true}
  FRAUD_HIGH_AMOUNT_THRESHOLD: ${FRAUD_HIGH_AMOUNT_THRESHOLD:-1000}


  # Location Rule
  FRAUD_RULES_LOCATION_ENABLED: ${FRAUD_RULES_LOCATION_ENABLED:-true}
  FRAUD_RULES_LOCATION_RISKY_VALUES: ${FRAUD_RULES_LOCATION_RISKY_VALUES:-UNKNOWN,RISKY-COUNTRY,NORTH-KOREA,IRAN}
  FRAUD_RULES_LOCATION_WHITELIST_VALUES: ${FRAUD_RULES_LOCATION_WHITELIST_VALUES:-SOUTH-AFRICA,NAMIBIA,BOTSWANA}

  # Velocity Rule
  FRAUD_RULES_VELOCITY_WINDOW_MINUTES: ${FRAUD_RULES_VELOCITY_WINDOW_MINUTES:-15}
  FRAUD_RULES_VELOCITY_MAX_COUNT: ${FRAUD_RULES_VELOCITY_MAX_COUNT:-5}

services:
  fraudengine-postgres:
    image: postgres:16
    container_name: fraudengine-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-frauddb}
      POSTGRES_USER: ${POSTGRES_USER:-frauduser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Fraud}
    ports:
      - "5432:5432"
    volumes:
      - fraud_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  fraudengine-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fraudengine:0.0.2
    container_name: fraudengine-app
    depends_on:
      fraudengine-postgres:
        condition: service_healthy
    # Load real values from docker/.env (gitignored)
    env_file:
      - docker/.env
    # Provide defaults and ensure the app sees all vars even if .env is missing
    environment:
      <<: *app-env
    ports:
      - "${SERVER_PORT:-8080}:8080"   # REST API
      - "${ISO8583_PORT:-8037}:8037"  # ISO8583 TCP
    restart: unless-stopped

volumes:
  fraud_pgdata:
